// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetchuser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const fetchUser = `-- name: FetchUser :one

SELECT id, created_at, updated_at, name FROM users WHERE id = $1
`

func (q *Queries) FetchUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, fetchUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
