// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getfeedbyurl.sql

package database

import (
	"context"
)

const getFeedbyURL = `-- name: GetFeedbyURL :one

SELECT id, created_at, updated_at, name, url, user_id FROM feeds WHERE url = $1
`

func (q *Queries) GetFeedbyURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedbyURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
