// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markfeed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getNextFeed = `-- name: GetNextFeed :one

SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at FROM feeds ORDER BY last_fetched_at ASC NULLS FIRST
LIMIT 1
`

func (q *Queries) GetNextFeed(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeed)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const markFeed = `-- name: MarkFeed :exec
UPDATE feeds
SET last_fetched_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkFeed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markFeed, id)
	return err
}
